apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-school
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
      - name:  my-container
        image: imagesnaresh.azurecr.io/samples/school
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: school
  labels:
    app: school
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: school

